name: Tests

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'
    - name: Install modules
      run: npm ci
    - name: Run ESLint
      run: npx eslint src/ --ext .js,.jsx,.ts,.tsx --format=node_modules/eslint/lib/cli-engine/formatters/stylish.js
    - name: Run tests
      run: npm run test
