name: Tests
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
       files: src/
    - name: Install modules
      run: npm ci
    - name: Run tests
      run: npm run test
